### PR TITLE
update to 1.2.0

### PR DESCRIPTION
**Pull request by proyan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jcarpent** [comment]
@conda-forge-admin, please rerender

**Comment by proyan** [comment]
The build.sh file still sets CppADCodegen=ON, so this won't yet compile for windows systems. @jcarpent Do you know how to setup different builds for different systems?

**Comment by jcarpent** [comment]
> The build.sh file still sets CppADCodegen=ON, so this won't yet compile for windows systems. @jcarpent Do you know how to setup different builds for different systems?

Windows uses the bld.bat file instead. This one should be updated accordingly.

**Comment by proyan** [comment]
Great. Thanks

**Review by jcarpent — APPROVED** [review]

**Pull request merged**
